# Site settings
title: Product Catalog
description: A curated collection of recommended products with sorting, filtering, and search capabilities.
baseurl: "" # Leave empty for GitHub Pages deployment
url: "https://rmnavz.github.io/RecommendedProductCatalog/" # Replace with your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-data

# Exclude files/folders from the build
exclude:
  - .github/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md
  - workflow.yml

# Include static files or folders in the build
include:
  - assets/

# Defaults for front matter
defaults:
  - scope:
      path: "" # Apply to all files
    values:
      layout: default
``
