name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
      - name: Install Jekyll and Dependencies
        run: |
          gem install bundler --user-install
          echo "$HOME/.local/share/gem/ruby/3.0.0/bin" >> $GITHUB_PATH  # Add gem executables to PATH
          export PATH="$HOME/.local/share/gem/ruby/3.0.0/bin:$PATH"  # Ensure the PATH is updated for the current session
          bundle install  # Install dependencies from Gemfile
        shell: /usr/bin/bash -e {0}
        env:
          GITHUB_PAGES: true
      - name: Build Jekyll Site
        run: bundle exec jekyll build  # Build the site
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # The directory where the site will be built

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
